version: 0.2

phases:
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Docker image..."
      - docker build -t my_httpd_image .
      - echo "Build completed on `date`"
